// Tool — English editorial content. Imported directly by Tool.jsx.
export default {
  // Pre-filled feedback email (floating CTA).
  feedbackSubject: 'OpenLegis — my feedback',
  feedbackBody: 'Hi!\n\nI tried OpenLegis and wanted to tell you that…\n\n',

  // Feedback CTA.
  feedbackTitle: 'Tell me what you think',
  feedbackHeading: 'Do you like the project?',
  feedbackSub: 'Let me know what you think →',

  // Empty answer from the agent.
  noAnswer: '(no answer)',

  // Error messages. message = raw text from the server.
  errAgent: (message) => `⚠️ Error reaching the agent: ${message}.`,
  errRate: (message) => `⏳ ${message}`,
  errAuth: (message) => `🔒 ${message}`,

  // Prompt generated by the "Ask the agent" click on a graph node.
  askAboutNode: (node) =>
    `Explain "${node.label || node.id}" and what Italian law establishes about it. Cite the articles.`,

  // App page SEO.
  seoTitle: 'App · query the law',
}
